### ISSUE TITLE
Cannot Select Multiple Sprites

### ISSUE THREAD

**Issue by punctdan** [yeoji/spritesheet-cutter#4]
I use this spritesheet. It lets me select a single sprite. But after selecting one, I cannot select more sprites by holding shift. Am I missing something? I think it would be much better to have an Export All button.

![CDE_rockstomp](https://github.com/yeoji/spritesheet-cutter/assets/46677171/c4088048-23c6-4b9a-9242-91ca501218e0)

**Comment by yeoji** [comment]
Hey @punctdan, I was able to select multiple sprites on your spritesheet:
![image](https://github.com/yeoji/spritesheet-cutter/assets/8002179/cfa2f2ef-8ea8-406f-8e7c-05b1a133e7c8)

Resulting zip of the selected ones above:
[sprite.zip](https://github.com/yeoji/spritesheet-cutter/files/14156073/sprite.zip)

Can you describe what happens when you hold shift and try to click on another sprite?

---

Edit: Also, thanks for the feedback :) I will try to look into having an Export All. The current method of selecting each sprite holding shift should still work for you though 🤞 I am using Chrome if that makes a difference.

**Comment by punctdan** [comment]
Thank you for the response. When I hold shift and try to click on another sprite, nothing happens. I tried it on Edge and Opera but it did not work. Interestingly, I can select multiple sprites without any problem when I use the example spritesheet. But not when using any custom ones.

![image](https://github.com/yeoji/spritesheet-cutter/assets/46677171/77235223-2a15-4dd0-a13e-446fc89a7bed)

**Comment by yeoji** [comment]
@punctdan Yeah that is weird, can you try with Chrome?

**Comment by punctdan** [comment]
> @punctdan Yeah that is weird, can you try with Chrome?

I just tried it on Chrome and the issue still persists.

**Comment by yeoji** [comment]
It's hard to say what the issue could be since I can't reproduce it. Do you have another sprite sheet that has the same problem?

**Comment by punctdan** [comment]
> It's hard to say what the issue could be since I can't reproduce it. Do you have another sprite sheet that has the same problem?

I did some testing by using different spritesheets from the same source. The tool was able to select multiple sprites from some spritesheets but not from other spritesheets. I even tried to trick it by uploading the same problematic spritesheet after succeeding on other ones. But it never worked on the problematic ones at all. It seems to be so random. :-(

### **Failing texture:**
![E_squatch](https://github.com/yeoji/spritesheet-cutter/assets/46677171/b1dab264-3d16-4ec6-8a28-e2aa57c1ab27)

### **Working texture:**
![monster_B](https://github.com/yeoji/spritesheet-cutter/assets/46677171/475472d9-41d9-4841-ae30-543b57ee7343)

**Comment by yeoji** [comment]
So the only time I'm able to reproduce this issue is when I:
1. Open the image
2. Shift to select works
3. Click on `Reload Current Image`
4. Shift to select doesn't work
5. Click on `Reload Current Image` again
6. Shift to select works

Edit: This also happens when I open another image. Clicking on `Reload Current Image` fixes the problem. Can you try doing that to see if that works for you?

![Screenshot 2024-02-06 at 10 40 05 pm](https://github.com/yeoji/spritesheet-cutter/assets/8002179/2c3755c4-c780-4418-b3d1-3ba619a0d8af)

**Comment by yeoji** [comment]
I found the problem but had to revert the fix because the build broke.

@punctdan, for now the workaround of reloading the image should work 🤞

**Comment by punctdan** [comment]
Thank you so much! It works when I follow your steps. So it all comes to that I need to reload the same image at least twice. What a strange issue. I'm glad you caught it up. 🎉

**Comment by yeoji** [comment]
Thanks for reporting ⭐ I'll fix it properly and let you know.

**Comment by yeoji** [comment]
@punctdan I've fixed the bug properly, and it should work without the need to reload the image now :)

**Comment by punctdan** [comment]
Awesome! Thank you for taking your time.
